<?php

/**
 * Контроллер отвечает за вывод данных для страницы "Города (/city)"
 */
class Controller_Widget_Data_City extends Controller_Widget_Data_Base
{


    protected $_view = 'w_city';


    public function before()
    {

        $this->_model = new Model_Data_City( App::$userFilter );

        parent::before(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function action_index()
    {
        parent::action_index();
    }
}