<?php

/**
 * Контроллер отвечает за вывод данных для страницы "Страны (/country)"
 */
class Controller_Widget_Data_Country extends Controller_Widget_Data_Base
{

    protected $_view = 'w_country';


    public function before()
    {

        $this->_model = new Model_Data_Country( App::$userFilter );

        parent::before(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws View_Exception
     */
    public function action_index()
    {

        parent::action_index();

    }
}