<?php

/**
 *  Ajax Подгрузка списков для фильтров
 *
 */
class Controller_Ajax_Filter_List extends Controller_Ajax
{

    /**
     *  объект Модели
     *
     * @var object
     */
    private $model;

    /**
     *  Готовый список для подгрузки в нужный элемент формы фильтра
     *
     * @var string
     */
    private $list;


    /**
     * @throws HTTP_Exception
     */
    public function before()
    {

        $this->model = Model::factory('Ajax_List');

        parent::before(); // TODO: Change the autogenerated stub
    }

    /**
     *  Список "Языки"
     *
     * @throws View_Exception
     */
    public function action_lngList()
    {

        $data['list'] = $this->model->getLngList();

        $this->list = View::factory('widgets/filters/list/w_lng_list', $data)->render();
    }

    /**
     *  Список "Формы правления"
     *
     * @throws View_Exception
     */
    public function action_govFormList()
    {

        $data['list'] = $this->model->getGovFormList();

        $this->list = View::factory('widgets/filters/list/w_govform_list', $data)->render();
    }

    /**
     *  Список "Страны"
     *
     * @throws View_Exception
     */
    public function action_countryList()
    {

        $data['list'] = $this->model->getCountryList();

        $this->list = View::factory('widgets/filters/list/w_country_list', $data)->render();
    }

    /**
     *
     */
    public function after()
    {
        $this->response->body($this->list);

        parent::after(); // TODO: Change the autogenerated stub
    }

}